# Generated by Django 4.2 on 2023-04-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
