# Generated by Django 4.2 on 2023-05-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
    ]
