# Generated by Django 4.2 on 2023-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_favourites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
